---
title: "Simulation Study"
output: html_document
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(echo = TRUE)
library(pdc)
library(simts)
```

## Simulation 1 

### Case 1: $n > p$ - adaptive greedy

```{r simu1_case1_adaptive, fig.align='center', cache = TRUE, fig.height=5, fig.width=6}
simu1_part1_ada <- run_simulation(nb_simu = 500, true_beta = c(1, rep(0,58), 1),
                              n = 80, n_star = 800, sigma = 1, cor_X = 0.5,
                              xlim = c(1.035, 1.095), ylim = c(0.02, 0.1),
                              xlab = expression(PE[y]), 
                              ylab = expression(MSE[beta]),
                              title = "Simulation 1: n > p",
                              adaptive = TRUE)
kable(simu1_part1_ada)  
```

### Case 2: $n > p$ - non-adaptive greedy

```{r simu1_case1_non_adaptive, fig.align='center', cache = TRUE, fig.height=5, fig.width=6}
simu1_part1_non_ada <- run_simulation(nb_simu = 500, true_beta = c(1, rep(0,58), 1),
                              n = 80, n_star = 800, sigma = 1, cor_X = 0.5,
                              xlim = c(1.035, 1.095), ylim = c(0.02, 0.1),
                              xlab = expression(PE[y]),
                              ylab = expression(MSE[beta]), 
                              title = "Simulation 1: n > p",
                              adaptive = FALSE) 
kable(simu1_part1_non_ada) 
```

### Case 3: $n < p$ - adaptive greedy

```{r simu1_case2_adaptive, fig.align='center', cache = TRUE, fig.height=5, fig.width=6}
simu1_part2_ada <- run_simulation(nb_simu = 500, true_beta = c(1, rep(0, 58), 1, rep(0, 100)),
                              n = 80, n_star = 800, sigma = 1, cor_X = 0.5,
                              xlim = c(1.045,1.22), ylim = c(0.03,0.23),
                              xlab = expression(PE[y]), 
                              ylab = expression(MSE[beta]),
                              title = "Simulation 1: n < p",
                              adaptive = TRUE)
kable(simu1_part2_ada) 
```

### Case 4: $n < p$ - non-adaptive greedy

```{r simu1_case2_nonadaptive, fig.align='center', cache = TRUE, fig.height=5, fig.width=6}
simu1_part2_non_ada <- run_simulation(nb_simu = 500, true_beta = c(1, rep(0, 58), 1, rep(0, 100)),
                              n = 80, n_star = 800, sigma = 1, cor_X = 0.5,
                              xlim = c(1.045,1.22), ylim = c(0.03,0.23),
                              xlab = expression(PE[y]), 
                              ylab = expression(MSE[beta]),
                              title = "Simulation 1: n < p",
                              adaptive = FALSE)
kable(simu1_part2_non_ada) 
```


## Simulation 2

### Case 1: $n > p$ - adaptive greedy

```{r simu2_case1_adaptive, fig.align='center', cache = TRUE, fig.height=5, fig.width=6}
simu2_part1_ada <- run_simulation(nb_simu = 500, true_beta = rep(c(0.3, 0), 5),
                              n = 100, n_star = 1000, sigma = 1, cor_X = 0.75,
                              xlim = c(1.065,1.17), ylim = c(0.18,0.46),
                              xlab = expression(PE[y]),
                              ylab = expression(MSE[beta]), 
                              title = "Simulation 2: n > p",
                              adaptive = TRUE)
kable(simu2_part1_ada) 
```

### Case 2: $n > p$ - non-adaptive greedy

```{r simu2_case1_non_adaptive, fig.align='center', cache = TRUE, fig.height=5, fig.width=6}
simu2_part1_nonada <- run_simulation(nb_simu = 500, true_beta = rep(c(0.3, 0), 5),
                              n = 100, n_star = 1000, sigma = 1, cor_X = 0.75,
                              xlim = c(1.065,1.17), ylim = c(0.18,0.46),
                              xlab = expression(PE[y]),
                              ylab = expression(MSE[beta]),
                              title = "Simulation 2: n > p", 
                              adaptive = FALSE)
kable(simu2_part1_nonada) 
```

### Case 3: $n < p$ - adaptive

```{r simu2_case2_adaptive, fig.align='center', cache = TRUE, fig.height=5, fig.width=6}
simu2_part2_ada <- run_simulation(nb_simu = 500, 
                                     true_beta = c(rep(c(0.3, 0), 5), rep(0, 100)),
                              n = 100, n_star = 1000, sigma = 1, cor_X = 0.75,
                              xlim = c(1.14,1.37), ylim = c(0.21,0.74),
                              xlab = expression(PE[y]),
                              ylab = expression(MSE[beta]),
                              title = "Simulation 2: n < p", 
                              adaptive = TRUE)
kable(simu2_part2_ada) 
```

### Case 4: $n < p$ - non-adaptive

```{r simu2_case2_non_adaptive, fig.align='center', cache = TRUE, fig.height=5, fig.width=6}
simu2_part2_non_ada <- run_simulation(nb_simu = 500, 
                                     true_beta = c(rep(c(0.3, 0), 5), rep(0, 100)),
                              n = 100, n_star = 1000, sigma = 1, cor_X = 0.75,
                              xlim = c(1.14,1.37), ylim = c(0.21,0.74),
                              xlab = expression(PE[y]),
                              ylab = expression(MSE[beta]),
                              title = "Simulation 2: n < p", 
                              adaptive = FALSE)
kable(simu2_part2_non_ada) 
```


## Simulation 3

### Case 1: $n > p$ - adaptive greedy

```{r simu3_case1_adaptive, fig.align='center', cache = TRUE, fig.height=5, fig.width=6}
beta <- c(rep(c(2,0,1),2),rep(0,16),rep(0.1,6),rep(0,16),rep(c(2,0,1),2))
simu3_part1_ada <- run_simulation(nb_simu = 500, true_beta = beta,
                              n = 100, n_star = 1000, sigma = 2, cor_X = 0.5,
                              xlim = c(4.73,5.4), ylim = c(0.79,1.8),
                              xlab = expression(PE[y]),
                              ylab = expression(MSE[beta]), 
                              title = "Simulation 3: n > p",
                              adaptive = TRUE)
kable(simu3_part1_ada) 
```

### Case 2: $n > p$ - non-adaptive greedy

```{r simu3_case1_nonadaptive, fig.align='center', cache = TRUE, fig.height=5, fig.width=6}
beta <- c(rep(c(2,0,1),2),rep(0,16),rep(0.1,6),rep(0,16),rep(c(2,0,1),2))
simu3_part1_nonada <- run_simulation(nb_simu = 500, true_beta = beta,
                              n = 100, n_star = 1000, sigma = 2, cor_X = 0.5,
                              xlim = c(4.73,5.4), ylim = c(0.79,1.8),
                              xlab = expression(PE[y]),
                              ylab = expression(MSE[beta]), 
                              title = "Simulation 3: n > p",
                              adaptive = FALSE)
kable(simu3_part1_nonada) 
```

### Case 3: $n < p$ - adaptive

```{r simu3_case2_adaptive, fig.align='center', cache = TRUE, fig.height=5, fig.width=6}
beta <- c(rep(c(2,0,1),2),rep(0,16),rep(0.1,6),rep(0,16),rep(c(2,0,1),2),
          rep(0,100))
simu3_part2_ada <- run_simulation(nb_simu = 500, true_beta = beta,
                              n = 100, n_star = 1000, sigma = 2, cor_X = 0.5,
                              xlim = c(4.85,5.9), ylim = c(1,2),
                              xlab = expression(PE[y]),
                              ylab = expression(MSE[beta]), 
                              title = "Simulation 3: n < p",
                              adaptive = TRUE)
kable(simu3_part2_ada) 
```



### Case 4: $n < p$ - non-adaptive

```{r simu3_case2_nonadaptive, fig.align='center', cache = TRUE, fig.height=5, fig.width=6}
beta <- c(rep(c(2,0,1),2),rep(0,16),rep(0.1,6),rep(0,16),rep(c(2,0,1),2),
          rep(0,100))
simu3_part2_non_ada <- run_simulation(nb_simu = 500, true_beta = beta,
                              n = 100, n_star = 1000, sigma = 2, cor_X = 0.5,
                              xlim = c(4.85,5.9), ylim = c(1,2),
                              xlab = expression(PE[y]),
                              ylab = expression(MSE[beta]), 
                              title = "Simulation 3: n < p",
                              adaptive = FALSE)
kable(simu3_part2_non_ada) 
```



